#!/bin/bash

CD="CocoaDialog.app/Contents/MacOS/CocoaDialog"
OLD_IFS="$IFS"
IFS=$'\n'
rv=($($CD inputbox --title "Download Youtube" --no-newline --informative-text "Enter youtube URL" --text "URL disini" --button1 "Unduh" --string-output))
echo -n "Downloading : "
echo ${rv[1]}
IFS="$OLD_IFS"

if [[ -z "${rv[1]}" ]]; then
echo "Gak jadi"
else
SCRIPT_PATH="youtube-dl"
PYTHON="/usr/bin/python"

$PYTHON $SCRIPT_PATH --update
$PYTHON $SCRIPT_PATH --newline -o '~/Movies/%(uploader)s/%(title)s-%(id)s.%(ext)s' ${rv[1]}
echo "Video[s] saved to ~/Movies/"
fi
